<?php
namespace AppBundle\Repository;

use AppBundle\Model\Definition\AbstractRepositoryModel;

/**
 * CareerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareerRepository extends AbstractRepositoryModel
{
    
}
