<?php

namespace AppBundle\Repository;

use AppBundle\Model\Definition\AbstractRepositoryModel;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends AbstractRepositoryModel
{
}
